---
title: "Draft Quarto document"
author: "Your Name"
format: html
---

## Header 1

```{r setup}
library(tidyverse)
library(targets)
tar_config_set(store = here::here("_targets"))
source(here::here("R/functions.R"))
lipidomics <- tar_read(lipidomics)
```

## Making a table

```{r}
```

```{r}
# Use it like this, which should give the same output as before.
create_table_descriptive_stats(lipidomics)
```

## Results: basic stats table

```{r}
tar_read(table_descriptive_stats) |>
  knitr::kable(
    caption = "The mean and standard deviation of metabolites in the lipidomics dataset"
  )
```

## Plot of distributions

```{r}
create_plot_distributions(lipidomics)
```

```{r}
tar_read(plot_distributions)
```

## Preparing the data

```{r}
clean(lipidomics)
```

## Preprocessing

```{r}
preprocess(lipidomics)
```

```{r}
just_cholesterol <- lipidomics |>
  dplyr::filter(metabolite == "Cholesterol") |>
  preprocess()
```

```{r}
glm(
  formula = class ~ value,
  data = just_cholesterol,
  family = binomial
) |>
  broom::tidy(exponentiate = TRUE) |>
  mutate(
    metabolite = unique(just_cholesterol$metabolite),
    model = format(class ~ value),
    .before = everything()
  )
```

## Fit model

```{r}
```

```{r}
```

## Model results

```{r}
```

```{r}
```

## Running multiple models

```{r}
just_cholesterol <- lipidomics |>
  filter(metabolite == "Cholesterol") |>
  preprocess()

lipidomics |>
  filter(metabolite == "Cholesterol") |>
  preprocess() |>
  fit_all_models()
```

## Split metabolites

```{r}
lipidomics |>
  dplyr::group_split(metabolite) |> 
  purrr::map(preprocess) |>
  purrr::map(fit_all_models) |>
  purrr::list_rbind()
```

## Appendix

```{r}
tar_read(model_results) |>
    knitr::kable(caption = "Results from the analysis from all metabolites and models.")
```

## This is poorly formatted

-   Definitely should have an empty space above this list.
-   This isn't a list, why not?
